import { PLUGIN_ID } from '../constants';

export const pluginActions = [
  {
    section: 'plugins',
    displayName: 'Read',
    uid: 'read',
    subCategory: 'general',
    pluginName: PLUGIN_ID,
  },
  {
    section: 'plugins',
    displayName: 'Manage workflows',
    uid: 'manage-workflows',
    subCategory: 'workflows',
    pluginName: PLUGIN_ID,
  },
  {
    section: 'plugins',
    displayName: 'Run workflows',
    uid: 'run',
    subCategory: 'workflows',
    pluginName: PLUGIN_ID,
  },
  {
    section: 'plugins',
    displayName: 'Backfill workflows',
    uid: 'backfill',
    subCategory: 'workflows',
    pluginName: PLUGIN_ID,
  },
  {
    section: 'plugins',
    displayName: 'Manage topic queue',
    uid: 'manage-topics',
    subCategory: 'topics',
    pluginName: PLUGIN_ID,
  },
  {
    section: 'plugins',
    displayName: 'View runs and errors',
    uid: 'view-runs',
    subCategory: 'runs',
    pluginName: PLUGIN_ID,
  },
  {
    section: 'plugins',
    displayName: 'Manage media catalog',
    uid: 'manage-media',
    subCategory: 'media',
    pluginName: PLUGIN_ID,
  },
  {
    section: 'plugins',
    displayName: 'View media usage',
    uid: 'view-media-usage',
    subCategory: 'media',
    pluginName: PLUGIN_ID,
  },
  {
    section: 'plugins',
    displayName: 'Manage social publishing',
    uid: 'manage-social',
    subCategory: 'social',
    pluginName: PLUGIN_ID,
  },
  {
    section: 'plugins',
    displayName: 'Run production audit',
    uid: 'run-audit',
    subCategory: 'audit',
    pluginName: PLUGIN_ID,
  },
  {
    section: 'plugins',
    displayName: 'Manage strategy planning',
    uid: 'manage-strategy',
    subCategory: 'growth',
    pluginName: PLUGIN_ID,
  },
  {
    section: 'plugins',
    displayName: 'View performance feedback',
    uid: 'view-performance',
    subCategory: 'growth',
    pluginName: PLUGIN_ID,
  },
  {
    section: 'plugins',
    displayName: 'Manage performance feedback',
    uid: 'manage-performance',
    subCategory: 'growth',
    pluginName: PLUGIN_ID,
  },
  {
    section: 'plugins',
    displayName: 'Manage homepage recommendations',
    uid: 'manage-homepage',
    subCategory: 'growth',
    pluginName: PLUGIN_ID,
  },
  {
    section: 'plugins',
    displayName: 'View audit trail',
    uid: 'view-audit-trail',
    subCategory: 'audit',
    pluginName: PLUGIN_ID,
  },
  {
    section: 'plugins',
    displayName: 'Manage autonomy policy',
    uid: 'manage-autonomy',
    subCategory: 'autopilot',
    pluginName: PLUGIN_ID,
  },
  {
    section: 'plugins',
    displayName: 'Manage ads autopilot',
    uid: 'manage-ads',
    subCategory: 'autopilot',
    pluginName: PLUGIN_ID,
  },
  {
    section: 'plugins',
    displayName: 'Activate ads autopilot',
    uid: 'activate-ads',
    subCategory: 'autopilot',
    pluginName: PLUGIN_ID,
  },
  {
    section: 'plugins',
    displayName: 'Pause ads autopilot',
    uid: 'pause-ads',
    subCategory: 'autopilot',
    pluginName: PLUGIN_ID,
  },
  {
    section: 'plugins',
    displayName: 'Manage video autopilot',
    uid: 'manage-video',
    subCategory: 'autopilot',
    pluginName: PLUGIN_ID,
  },
  {
    section: 'plugins',
    displayName: 'Render video assets',
    uid: 'render-video',
    subCategory: 'autopilot',
    pluginName: PLUGIN_ID,
  },
  {
    section: 'plugins',
    displayName: 'View traffic snapshots',
    uid: 'view-traffic',
    subCategory: 'autopilot',
    pluginName: PLUGIN_ID,
  },
  {
    section: 'plugins',
    displayName: 'Import traffic snapshots',
    uid: 'import-traffic',
    subCategory: 'autopilot',
    pluginName: PLUGIN_ID,
  },
  {
    section: 'plugins',
    displayName: 'Manage growth experiments',
    uid: 'manage-experiments',
    subCategory: 'autopilot',
    pluginName: PLUGIN_ID,
  },
  {
    section: 'plugins',
    displayName: 'View provider status',
    uid: 'view-provider-status',
    subCategory: 'autopilot',
    pluginName: PLUGIN_ID,
  },
  {
    section: 'plugins',
    displayName: 'Test provider readiness',
    uid: 'test-provider-readiness',
    subCategory: 'autopilot',
    pluginName: PLUGIN_ID,
  },
] as const;
