name: Production Deploy V3

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: subscribe-it
  API_IMAGE: star-sign-api
  FRONTEND_IMAGE: star-sign-frontend

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "E ok"
